---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${SERVICE_NAME}
  namespace: ${NAMESPACE}
data:  
  appsettings.json.template: |-
    {
      "RedisConfig": {
        "TimeCookieExpire": "14400",
        "CookieDomainList": "vplay.vn",
        "CookieNameList": ".vplay.vn",
        "RedisIp": "redis-master.services.svc.cluster.local",
        "RedisPort": "6379",
        "RedisPassword": ""
      },
      "DbConfig": {
        "CONNECTION": "10.54.10.78",
        "SQLPASS": "User ID=allvalk;Password=Vinh312@"
      },
      "Mongo": {
        "IpAddress": "mongodb://admin:123123@10.54.10.62:27017/EventTet?authSource=admin"
      },
      "ConnectLink": {
        "Authen": "https://dev-id.vplay.vn/api-core/v1/authen-service/",
        "Userinfo": "https://dev-id.vplay.vn/api-core/v1/authen-service/users/",
        "Billing": "https://dev-id.vplay.vn/api-core/v1/payment-service/",
        "Event": "https://dev-game-event-wheel-api.vplay.vn/v1/"
      },      
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft": "Warning",
          "Microsoft.Hosting.Lifetime": "Information"
        }
      },
      "Info": {
        "clientId": "0cfe3f835b054b50",
        "clientSecret": "ZUUwZ/50sMATFBzVc4Wo1uiQ5O+4bKKzuPr7ST92gFXjk2H4FXt3GFiiYQ5mGW+w",
        "eventId": "1"
      },
      "AllowedHosts": "*"
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${SERVICE_NAME}
  namespace: ${NAMESPACE}
spec:
  selector:
    matchLabels:
      service: ${SERVICE_NAME}
  replicas: 1
  template:
    metadata:
      labels:
        service: ${SERVICE_NAME}
        logger: nlog
      annotations:
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: ${SERVICE_NAME}
        image: ${IMAGE}
        env:
        - name: TZ
          value: Etc/GMT-7
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        ports:
        - containerPort: ${CONTAINER_PORT}
        volumeMounts:
          - name: ${SERVICE_NAME}
            mountPath: /app/appsettings.json.template
            subPath: appsettings.json.template
      nodeSelector:
      imagePullSecrets:
      - name: registry
      restartPolicy: Always
      volumes:
      - name: ${SERVICE_NAME}
        configMap: 
          name: ${SERVICE_NAME}
---
apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE_NAME}
  namespace: ${NAMESPACE}
spec:
  ports:
  - port: ${CONTAINER_PORT}
    protocol: TCP
  selector:
    service: ${SERVICE_NAME}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  ${SERVICE_NAME}
  namespace: ${NAMESPACE}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: ${DOMAIN}
    http:
      paths:
      - path: ${SERVICE_PATH}(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: ${SERVICE_NAME}
            port:
              number: ${CONTAINER_PORT}

